### ISSUE TITLE
`pshmem.h` header is not usable

### ISSUE THREAD

**Issue by bertwesarg** [openshmem-org/osss-ucx#2]
I found the following issues:

* [x] invalid `unsiged` in front of `intX_t` types. just use `uintX_t` instead
* [x] Typo `_void`  [here](https://github.com/openshmem-org/osss-ucx/blob/cf5f088d2a13c47cf851c5e8d39800ecc4b1487c/include/pshmem.h#L96)
* [x] Unknown type `shmem_cmp_t`
* [x] Multiple typos `intX` instead of `intX_t`
* [x] `const` missmatches between:
     * all `shmem_*_g`
     * all reduce functions

**Comment by bertwesarg** [comment]
@tonycurtis Have you fixed any these issue already, or why are some of the tasks marked as done?

**Comment by tonycurtis** [comment]
And done the unsigned int<N> ones
