### ISSUE TITLE
Error while running reference implementation

### ISSUE THREAD

**Issue by nsarka** [openshmem-org/osss-ucx#4]
Hi Dr. Curtis,

I am trying to build and run the openshmem-examples with the reference implementation but I am receiving this error:

```
[sarkauskas@storage01 C]$ oshcc hello.c -o hello && mpiexec -hostfile ~/hostfile -np 1 --oversubscribe hello
[storage01:13147:0:13147] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x49)

/home/sarkauskas/osss-ucx/src/shmemc/ucx/comms.c: [ lookup_rkey() ]
      ...
       35 lookup_rkey(size_t region, int pe)
       36 {
       37     return proc.comms.regions[region].minfo[pe].racc.rkey;
==>    38 }
       39
       40 /*
       41  * where the heap lives on PE "pe"

==== backtrace ====
 0 0x0000000000005592 lookup_rkey()  /home/sarkauskas/osss-ucx/src/shmemc/ucx/comms.c:38
 1 0x0000000000005592 get_remote_key_and_addr()  /home/sarkauskas/osss-ucx/src/shmemc/ucx/comms.c:129
 2 0x0000000000005592 shmemc_ctx_put()  /home/sarkauskas/osss-ucx/src/shmemc/ucx/comms.c:649
 3 0x000000000001a405 shmem_ctx_long_put()  /home/sarkauskas/osss-ucx/src/putget.c:75
 4 0x000000000001a405 shmem_ctx_long_put()  /home/sarkauskas/osss-ucx/src/putget.c:75
 5 0x000000000001e1e8 shmem_long_p()  /home/sarkauskas/osss-ucx/src/putget.c:705
 6 0x000000000000b238 barrier_sync_helper_binomial_tree()  /home/sarkauskas/osss-ucx/src/collectives/shcoll/src/barrier.c:145
 7 0x000000000000b238 shcoll_barrier_all_binomial_tree()  /home/sarkauskas/osss-ucx/src/collectives/shcoll/src/barrier.c:270
 8 0x00000000004009fc main()  ???:0
 9 0x0000000000021c05 __libc_start_main()  ???:0
10 0x0000000000400919 _start()  ???:0
===================
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 13147 on node storage01 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
[sarkauskas@storage01 C]$
```

My configuration options are
```
$ ./configure --prefix=/home/sarkauskas/osss-ucx/install --with-pmix=/home/sarkauskas/dependencies/pmix-3.1.0rc5/install/ --with-ucx=/home/sarkauskas/dependencies/ucx/install --enable-threads
```

My ucx configuration options are
```
./configure --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --enable-mt --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/home/sarkauskas/dependencies/ucx/install --enable-mt
```

My pmix configuration options are
```
./configure --prefix=/home/sarkauskas/dependencies/pmix-3.1.0rc5/install --enable-debug
```

I apologize if this is the wrong place to put this, but any advice/help would be greatly appreciated.

Thanks,
Nick

**Comment by tonycurtis** [comment]
> On Jan 18, 2019, at 1:44 PM, Nick Sarkauskas <notifications@github.com> wrote:
> 
> Hi Dr. Curtis,
> 
> I am trying to build and run the openshmem-examples with the reference implementation but I am receiving this error:
> 
> `[sarkauskas@storage01 C]$ oshcc hello.c -o hello && mpiexec -hostfile ~/hostfile -np 1 --oversubscribe hello
> [storage01:13147:0:13147] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x49)
> 
> /home/sarkauskas/osss-ucx/src/shmemc/ucx/comms.c: [ lookup_rkey() ]
> ...
> 35 lookup_rkey(size_t region, int pe)
> 36 {
> 37 return proc.comms.regions[region].minfo[pe].racc.rkey;
> ==> 38 }
> 39
> 40 /*
> 41 * where the heap lives on PE “pe"
> 

Hi (and the name’s Tony):

Which versions of UCX and MPI are you using?

tony

**Comment by nsarka** [comment]
Hi Tony (sorry),

I'm running the master branch of https://github.com/openucx/ucx for ucx and openmpi-4.0.0

Thanks,
Nick

**Comment by tonycurtis** [comment]
> On Jan 18, 2019, at 2:00 PM, Nick Sarkauskas <notifications@github.com> wrote:
> 
> Hi Tony (sorry),
> 
> I'm running the master branch of https://github.com/openucx/ucx <https://github.com/openucx/ucx> for ucx and openmpi-4.0.0
> 

I suspect it is a problem of interaction between OpenMPI 4 and PMIx 3.  PMIx 2.1.1 should work with OpenMPI 4.

tony

**Comment by nsarka** [comment]
Thank you. I'll give PMIx 2.1.1 a shot.

**Comment by nsarka** [comment]
That was it! Thanks so much.
